ADM-857:[backend]feat: new Github action to see if it can check committer name

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -228,21 +228,22 @@ jobs:
         run: |
           ./ops/check.sh frontend-license
 
-  #  check-buildkite-status:
-  #    if: ${{ github.event_name == 'pull_request' }}
-  #    runs-on: ubuntu-latest
-  #    steps:
-  #      - name: Checkout code
-  #        uses: actions/checkout@v4
-  #
-  #      - name: Check BuildKite status
-  #        run: |
-  #          buildkite_status=$(curl -H "Authorization: Bearer ${{ secrets.BUILDKITE_TOKEN }}" "https://api.buildkite.com/v2/organizations/thoughtworks-Heartbeat/pipelines/heartbeat/builds?branch=main"| jq -r '.[0].state')
-  #
-  #          if [ "$buildkite_status" != "passed" ]; then
-  #            echo "BuildKite build failed. Cannot merge the PR."
-  #            exit 1
-  #          fi
+    check-buildkite-status:
+      if: ${{ github.event_name == 'pull_request' }}
+      runs-on: ubuntu-latest
+      steps:
+        - name: Checkout code
+          uses: actions/checkout@v4
+
+        - name: Check BuildKite status
+          run: |
+#            buildkite_status=$(curl -H "Authorization: Bearer ${{ secrets.BUILDKITE_TOKEN }}" "https://api.buildkite.com/v2/organizations/thoughtworks-Heartbeat/pipelines/heartbeat/builds?branch=main"| jq -r '.[0].state')
+            buildkite_status=failed
+            if [ "$buildkite_status" != "passed" ]; then
+              echo "BuildKite build failed. Cannot merge the PR."
+              echo ${{ github.event.pull_request.user.login }}
+              exit 1
+            fi
   images-check:
     runs-on: ubuntu-latest
     steps:
