ADM-857:[backend]feat: completed name comparison

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -235,34 +235,37 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-#      - name: Check BuildKite status
-#        run: |
-#          buildkite_status=$(curl -H "Authorization: Bearer ${{ secrets.BUILDKITE_TOKEN }}" "https://api.buildkite.com/v2/organizations/heartbeat-backup/pipelines/heartbeat/builds?branch=main"| jq -r '.[0].state')
-#
-#          if [ "$buildkite_status" != "passed" ]; then
-#            echo "BuildKite build failed. Cannot merge the PR."
-#            exit 1
-#          fi
+      - name: Check BuildKite status
+        run: |
+          buildkite_status=$(curl -H "Authorization: Bearer ${{ secrets.BUILDKITE_TOKEN }}" "https://api.buildkite.com/v2/organizations/heartbeat-backup/pipelines/heartbeat/builds?branch=main"| jq -r '.[0].state')
 
-      - name: Check for Username Match with GitHub API on Specific Branch
+          if [ "$buildkite_status" != "passed" ]; then
+            echo "BuildKite build failed. Cannot merge the PR."
+            exit 1
+          fi
+
+      - name: Check for Username Match with GitHub API
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          SPECIFIC_BRANCH="ADM-857-w"
+          # 使用GitHub API获取最近的commit信息
+          LATEST_COMMIT=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+          "https://api.github.com/repos/${{ github.repository }}/commits?per_page=1" | jq -r '.[0].author.login')
 
-          LATEST_COMMIT="${{ github.event.commits[0].author.name }}"
-
+          # 获取当前trigger的GitHub用户名
           CURRENT_ACTOR="${{ github.actor }}"
 
           echo "Latest Commit Author Login: $LATEST_COMMIT"
           echo "Current Actor: $CURRENT_ACTOR"
 
+          # 比较用户名
           if [ "$CURRENT_ACTOR" != "$LATEST_COMMIT" ]; then
             echo "No match"
-            echo "The last commit was made by: $LATEST_COMMIT on branch $SPECIFIC_BRANCH"
+            echo "The last commit was made by: $LATEST_COMMIT"
+            exit 1
           else
             echo "Match"
-            echo "Both actions were performed by: $CURRENT_ACTOR on branch $SPECIFIC_BRANCH"
+            echo "Both actions were performed by: $CURRENT_ACTOR"
           fi
   images-check:
     runs-on: ubuntu-latest
